project: calipso-3dcnn

data:
  train_static_roots: ["./data/demo/simplified_train_demo"]
  train_dynamic_roots: [""]
  infer_roots: ["./data/demo/infer_spiral_demo"]

  train_static_prep_roots: ["./data/demo/simplified_train_demo_preprocessed"]
  train_dynamic_prep_roots: [""]
  infer_prep_roots: ["./data/demo/infer_spiral_demo_preprocessed"]

labeling:
  labeled_inference: False
  start_point: [20, 20, 20]
  move_axis: ["-z", "-x", "-y", "+z", "+x", "+y"]
  inference_save_rpath: "./outputs/infer_spiral_result.csv"

model_io:
  save_dir: "./weights/demo"
  train_resume: False
  best_model: "spiral_best_model.pth"
  latest_ckpt: "spiral_latest_checkpoint.pth"

grid:
  num_classes_x: 21
  num_classes_y: 21
  num_classes_z: 21

train:
  asym_head: False
  total_epochs: 20
  batch_size: 512
  lr: 1.0e-4
  weight_decay: 1.0e-4
  z_loss_weight: 1.25
  num_workers: 0
  prefetch: 4
  val_split: 0.10
  test_split: 0.10
  seed: 42
  hidden_dim: 1024
  dropout_p: 0.3
  focal_switch_epoch: 30

input_spec:
  clip_length: 6
  clip_stride: 1
  channels: 1
  height: 8
  width: 30
  rows_per_frame: 60

inference:
  stride: 1
  confidence_thresh: 0.7
  min_stable_count: 3
  smoothing_window: 200
  max_distance_threshold: 8

net:
  server_ip: "0.0.0.0"
  client_target_ip: "127.0.0.1"
  pull_port: 5555
  pub_port: 5556
  topic: "traj"

frame:
  seq_num_bytes: 8
  frame_bits: 240
  bitorder: "little"

client:
  send_hz: 300